### ISSUE TITLE
Arduino Build Fails

### ISSUE THREAD

**Issue by suculent** [suculent/thinx-device-api#373]
Without any meaningful error. Builds MUST be tested separately, not as a part of the main repo.

```
2022-04-30T18:26:01.299924293Z Current path: /mnt/data/repos/cedc16bb6bb06daaa3ff6d30666d91aacd6e3efbf9abbc151b4dcade59af7c12/14edd1a0-5d35-11e8-9099-57dcf9395a29/ddab2ec0-c8b2-11ec-a7ae-8f80a1d38a7e/thinx-firmware-esp8266-ino
2022-04-30T18:26:01.299928325Z total 28
2022-04-30T18:26:01.299931900Z drwxr-xr-x    4 root     root          4096 Apr 30 18:25 .
2022-04-30T18:26:01.299935626Z drwxrwxrwx    4 root     root          4096 Apr 30 18:25 ..
2022-04-30T18:26:01.299939572Z -rw-r--r--    1 root     root           274 Apr 30 18:25 .codacy.yml
2022-04-30T18:26:01.299943371Z drwxr-xr-x    8 root     root          4096 Apr 30 18:25 .git
2022-04-30T18:26:01.299947015Z -rw-r--r--    1 root     root           469 Apr 30 18:25 .gitignore
2022-04-30T18:26:01.299950652Z -rw-r--r--    1 root     root           474 Apr 30 18:25 .gitmodules
2022-04-30T18:26:01.299954762Z -rw-rw-rw-    1 root     root           985 Apr 30 18:25 LICENSE.md
2022-04-30T18:26:01.299958698Z -rw-rw-rw-    1 root     root          4359 Apr 30 18:25 README.md
2022-04-30T18:26:01.299962367Z -rw-rw-rw-    1 root     root           443 Apr 30 18:25 disabled_circle.yml
2022-04-30T18:26:01.299966136Z -rw-rw-rw-    1 root     root          2039 Apr 30 18:25 prerelease.sh
2022-04-30T18:26:01.299969967Z -rw-rw-rw-    1 root     root           220 Apr 30 18:25 sonar-project.properties
2022-04-30T18:26:01.299974199Z drw-rw-rw-    3 root     root          4096 Apr 30 18:25 thinx-esp8266-example
2022-04-30T18:26:01.299979235Z -rw-rw-rw-    1 root     root           412 Apr 30 18:25 thinx.yml
2022-04-30T18:26:01.299986484Z -rw-r--r--    1 root     root           704 Apr 30 18:25 thinx_build.json
2022-04-30T18:26:01.299994741Z Updating submodules...
2022-04-30T18:26:01.300000515Z Submodule path 'thinx-esp8266-example/lib/PubSubClient': checked out 'd911d766c974772cddc1e7f173ba8caba3c6d28f'
2022-04-30T18:26:01.300005882Z Submodule path 'thinx-esp8266-example/lib/WiFiManager': checked out '368ea928f014be9c1616b1a94caf81a8971142ee'
2022-04-30T18:26:01.300011138Z Fetched commit ID: 9a242566d66af2e90abe1653af5bc63fd9ef65db
2022-04-30T18:26:01.300016637Z Repository version/revision: 75
2022-04-30T18:26:01.300021937Z Searching THiNX-File in /mnt/data/repos/cedc16bb6bb06daaa3ff6d30666d91aacd6e3efbf9abbc151b4dcade59af7c12/14edd1a0-5d35-11e8-9099-57dcf9395a29/ddab2ec0-c8b2-11ec-a7ae-8f80a1d38a7e/thinx-firmware-esp8266-ino...
2022-04-30T18:26:01.300027414Z Building for platform 'arduino' in language 'C/C++'...
2022-04-30T18:26:01.300032811Z Running DevSec...
2022-04-30T18:26:01.300037665Z No environment.json found
2022-04-30T18:26:01.300042520Z Building for arduino in WORKDIR: /mnt/data/repos/cedc16bb6bb06daaa3ff6d30666d91aacd6e3efbf9abbc151b4dcade59af7c12/14edd1a0-5d35-11e8-9099-57dcf9395a29/ddab2ec0-c8b2-11ec-a7ae-8f80a1d38a7e/thinx-firmware-esp8266-ino
2022-04-30T18:26:01.300047763Z [arduino] WARNING! No THiNX-File found! in /mnt/data/repos/cedc16bb6bb06daaa3ff6d30666d91aacd6e3efbf9abbc151b4dcade59af7c12/14edd1a0-5d35-11e8-9099-57dcf9395a29/ddab2ec0-c8b2-11ec-a7ae-8f80a1d38a7e/thinx-firmware-esp8266-ino: 
2022-04-30T18:26:01.300058285Z thinx_build-ZMU8z3JQsgKQPfhh.1.gd2y5uv3qqpy@core    | arduino-docker-build-0.8.6
2022-04-30T18:26:01.300063225Z thinx_build-ZMU8z3JQsgKQPfhh.1.gd2y5uv3qqpy@core    | 
2022-04-30T18:26:01.300068602Z thinx_build-ZMU8z3JQsgKQPfhh.1.gd2y5uv3qqpy@core    | - board: espressif:esp8266:d1_mini_pro
2022-04-30T18:26:01.300073660Z thinx_build-ZMU8z3JQsgKQPfhh.1.gd2y5uv3qqpy@core    | - flash_size: 16M
2022-04-30T18:26:01.300078751Z thinx_build-ZMU8z3JQsgKQPfhh.1.gd2y5uv3qqpy@core    | - f_cpu: 80000000L
2022-04-30T18:26:01.300084144Z thinx_build-ZMU8z3JQsgKQPfhh.1.gd2y5uv3qqpy@core    | - ENVOUT: /opt/workspace/thinx-esp8266-example/environment.h
2022-04-30T18:26:01.300089222Z thinx_build-ZMU8z3JQsgKQPfhh.1.gd2y5uv3qqpy@core    | - libs: 
2022-04-30T18:26:01.300094670Z thinx_build-ZMU8z3JQsgKQPfhh.1.gd2y5uv3qqpy@core    | - flash_ld: eagle.flash.4m1m.ld (esp8266)
2022-04-30T18:26:01.300099592Z thinx_build-ZMU8z3JQsgKQPfhh.1.gd2y5uv3qqpy@core    | - test_script: 0
2022-04-30T18:26:01.300104493Z thinx_build-ZMU8z3JQsgKQPfhh.1.gd2y5uv3qqpy@core    | No environment.json found
2022-04-30T18:26:01.300112041Z thinx_build-ZMU8z3JQsgKQPfhh.1.gd2y5uv3qqpy@core    | Simulating screen in headless mode, use socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:"" 
2022-04-30T18:26:01.300118475Z thinx_build-ZMU8z3JQsgKQPfhh.1.gd2y5uv3qqpy@core    | Cleaning libraries...
2022-04-30T18:26:01.300124083Z thinx_build-ZMU8z3JQsgKQPfhh.1.gd2y5uv3qqpy@core    | Installing library THiNX...
2022-04-30T18:26:01.300129492Z [arduino] Docker completed <<<
2022-04-30T18:26:01.300135716Z [arduino] Docker build failed, no firmware.bin found.
2022-04-30T18:26:01.300141092Z Could not find outfile /mnt/data/deploy/cedc16bb6bb06daaa3ff6d30666d91aacd6e3efbf9abbc151b4dcade59af7c12/14edd1a0-5d35-11e8-9099-57dcf9395a29/ddab2ec0-c8b2-11ec-a7ae-8f80a1d38a7e/firmware.bin...
2022-04-30T18:26:01.300146761Z Could not find outfile /mnt/gluster/thinx/deploy/cedc16bb6bb06daaa3ff6d30666d91aacd6e3efbf9abbc151b4dcade59af7c12/14edd1a0-5d35-11e8-9099-57dcf9395a29/ddab2ec0-c8b2-11ec-a7ae-8f80a1d38a7e/firmware.bin anywhere...
2022-04-30T18:26:01.300152617Z [builder] Build Stage completed with status: FAILED
2022-04-30T18:26:01.300158000Z [builder] Post-flight check...
2022-04-30T18:26:01.300163637Z JOB-RESULT: {"build_id":"ddab2ec0-c8b2-11ec-a7ae-8f80a1d38a7e","commit":"9a242566d66af2e90abe1653af5bc63fd9ef65db","thx_version":1,"git_repo":"https://github.com/suculent/thinx-firmware-esp8266-ino.git","outfile":"<none>","udid":"14edd1a0-5d35-11e8-9099-57dcf9395a29","sha":0,"owner":"cedc16bb6bb06daaa3ff6d30666d91aacd6e3efbf9abbc151b4dcade59af7c12","status":"FAILED","platform":"arduino","version":"thinx-firmware-esp8266-ino:2.8.238","md5":0,"env_hash":"cafebabe"}
```

**Comment by suculent** [comment]
New error:
```
In file included from /root/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266/HardwareSerial.cpp:30:
/root/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266/PolledTimeout.h: In instantiation of 'static constexpr esp8266::polledTimeout::TimePolicy::TimeUnit<TimeSourceType, second_th>::timeType esp8266::polledTimeout::TimePolicy::TimeUnit<TimeSourceType, second_th>::computeRangeCompensation() [with TimeSourceType = esp8266::polledTimeout::TimePolicy::TimeSourceCycles; long long unsigned int second_th = 1000; esp8266::polledTimeout::TimePolicy::TimeUnit<TimeSourceType, second_th>::timeType = unsigned int]':
/root/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266/PolledTimeout.h:122:78:   required from 'constexpr const timeType esp8266::polledTimeout::TimePolicy::TimeUnit<esp8266::polledTimeout::TimePolicy::TimeSourceCycles, 1000>::rangeCompensate'
/root/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266/PolledTimeout.h:123:75:   required from 'constexpr const timeType esp8266::polledTimeout::TimePolicy::TimeUnit<esp8266::polledTimeout::TimePolicy::TimeSourceCycles, 1000>::user2UnitMultiplierMax'
/root/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266/PolledTimeout.h:127:99:   required from 'constexpr const timeType esp8266::polledTimeout::TimePolicy::TimeUnit<esp8266::polledTimeout::TimePolicy::TimeSourceCycles, 1000>::timeMax'
/root/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266/PolledTimeout.h:228:25:   required from 'static constexpr esp8266::polledTimeout::timeoutTemplate<PeriodicT, YieldPolicyT, TimePolicyT>::timeType esp8266::polledTimeout::timeoutTemplate<PeriodicT, YieldPolicyT, TimePolicyT>::timeMax() [with bool PeriodicT = false; YieldPolicyT = esp8266::polledTimeout::YieldPolicy::DoNothing; TimePolicyT = esp8266::polledTimeout::TimePolicy::TimeUnit<esp8266::polledTimeout::TimePolicy::TimeSourceCycles, 1000>; esp8266::polledTimeout::timeoutTemplate<PeriodicT, YieldPolicyT, TimePolicyT>::timeType = unsigned int]'
/root/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266/PolledTimeout.h:188:70:   required from 'void esp8266::polledTimeout::timeoutTemplate<PeriodicT, YieldPolicyT, TimePolicyT>::reset(esp8266::polledTimeout::timeoutTemplate<PeriodicT, YieldPolicyT, TimePolicyT>::timeType) [with bool PeriodicT = false; YieldPolicyT = esp8266::polledTimeout::YieldPolicy::DoNothing; TimePolicyT = esp8266::polledTimeout::TimePolicy::TimeUnit<esp8266::polledTimeout::TimePolicy::TimeSourceCycles, 1000>; esp8266::polledTimeout::timeoutTemplate<PeriodicT, YieldPolicyT, TimePolicyT>::timeType = unsigned int]'
/root/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266/PolledTimeout.h:154:10:   required from 'esp8266::polledTimeout::timeoutTemplate<PeriodicT, YieldPolicyT, TimePolicyT>::timeoutTemplate(esp8266::polledTimeout::timeoutTemplate<PeriodicT, YieldPolicyT, TimePolicyT>::timeType) [with bool PeriodicT = false; YieldPolicyT = esp8266::polledTimeout::YieldPolicy::DoNothing; TimePolicyT = esp8266::polledTimeout::TimePolicy::TimeUnit<esp8266::polledTimeout::TimePolicy::TimeSourceCycles, 1000>; esp8266::polledTimeout::timeoutTemplate<PeriodicT, YieldPolicyT, TimePolicyT>::timeType = unsigned int]'
/root/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266/HardwareSerial.cpp:140:64:   required from here
/root/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266/PolledTimeout.h:111:75: error: '(1.0e+3 / 0.0)' is not a constant expression
  111 |       constexpr double number_of_secondTh_in_one_tick = (1.0 * second_th) / ticksPerSecond;
      |                                                         ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
exit status 1
No lint results found.
THiNX BUILD FAILED: 1

```

**Comment by suculent** [comment]
There's currently problem with fetching libraries on the run (container had no DNS). Otherwise locally the path is ready.

**Comment by suculent** [comment]
This is caused by Arduino Core since 2.7.4. Builder is currently pinned to 2.6.3, until this gets solved. Examples build well on 3.0.2 locally, so those can be considered prepared.
